// Villes/communes principales par wilaya, utilisées pour filtrer le champ "Ville"
// en fonction de la wilaya sélectionnée. Liste non exhaustive (l'Algérie compte
// 1541 communes) mais couvre les localités les plus connues de chaque wilaya.
export const VILLES_PAR_WILAYA = {
  "Adrar": ["Adrar", "Reggane", "Aoulef", "Zaouiet Kounta", "Tsabit", "Fenoughil", "Bouda", "Sali", "Akabli"],
  "Chlef": ["Chlef", "Ténès", "Boukadir", "Oued Fodda", "El Karimia", "Ouled Farès", "Sobha", "Beni Haoua"],
  "Laghouat": ["Laghouat", "Aflou", "Ksar El Hirane", "Hassi R'Mel", "Brida", "Gueltat Sidi Saad"],
  "Oum El Bouaghi": ["Oum El Bouaghi", "Aïn Beïda", "Aïn M'lila", "Ksar Sbahi", "Sigus", "Meskiana"],
  "Batna": ["Batna", "Barika", "Merouana", "Arris", "N'Gaous", "Tazoult", "Ras El Aioun"],
  "Béjaïa": ["Béjaïa", "Akbou", "Kherrata", "Amizour", "Sidi Aïch", "El Kseur", "Souk El Ténine", "Tichy"],
  "Biskra": ["Biskra", "Tolga", "Sidi Okba", "Zeribet El Oued", "El Kantara", "Djemorah"],
  "Béchar": ["Béchar", "Kenadsa", "Abadla", "Taghit", "Beni Ounif", "Igli"],
  "Blida": ["Blida", "Boufarik", "Bouinan", "El Affroun", "Larbaâ", "Mouzaïa", "Ouled Yaich"],
  "Bouira": ["Bouira", "Lakhdaria", "M'Chedallah", "Sour El Ghozlane", "Aïn Bessem", "Kadiria"],
  "Tamanrasset": ["Tamanrasset", "Abalessa", "Idlès", "Tazrouk"],
  "Tébessa": ["Tébessa", "Bir El Ater", "Chéria", "El Aouinet", "Ouenza", "Morsott"],
  "Tlemcen": ["Tlemcen", "Maghnia", "Nedroma", "Remchi", "Ghazaouet", "Sebdou", "Beni Mester"],
  "Tiaret": ["Tiaret", "Sougueur", "Frenda", "Ksar Chellala", "Mahdia", "Rahouia"],
  "Tizi Ouzou": ["Tizi Ouzou", "Azazga", "Draâ Ben Khedda", "Ouadhias", "Boghni", "Larbaâ Nath Irathen", "Freha"],
  "Alger": ["Alger Centre", "Bab El Oued", "Hussein Dey", "El Harrach", "Bir Mourad Raïs", "Dar El Beïda", "Bordj El Kiffan", "Kouba", "Bab Ezzouar", "Zeralda", "Chéraga", "Rouiba"],
  "Djelfa": ["Djelfa", "Aïn Oussera", "Messaad", "Hassi Bahbah", "Birine", "El Idrissia"],
  "Jijel": ["Jijel", "Taher", "El Milia", "Chekfa", "Ziama Mansouriah", "Emir Abdelkader"],
  "Sétif": ["Sétif", "El Eulma", "Aïn Oulmène", "Bougaa", "Aïn Azel", "Béni Aziz", "Ras El Oued"],
  "Saïda": ["Saïda", "Aïn El Hadjar", "El Hassasna", "Youb", "Sidi Boubekeur"],
  "Skikda": ["Skikda", "Azzaba", "Collo", "El Harrouch", "Ramdane Djamel", "Tamalous"],
  "Sidi Bel Abbès": ["Sidi Bel Abbès", "Telagh", "Ben Badis", "Sfisef", "Mostefa Ben Brahim", "Tessala"],
  "Annaba": ["Annaba", "El Bouni", "El Hadjar", "Berrahal", "Séraïdi"],
  "Guelma": ["Guelma", "Oued Zenati", "Bouchegouf", "Héliopolis", "Hammam Débagh"],
  "Constantine": ["Constantine", "El Khroub", "Hamma Bouziane", "Didouche Mourad", "Aïn Smara", "Zighoud Youcef"],
  "Médéa": ["Médéa", "Berrouaghia", "Ksar El Boukhari", "Tablat", "Ouzera", "Béni Slimane"],
  "Mostaganem": ["Mostaganem", "Sidi Ali", "Bouguirat", "Achaacha", "Aïn Nouissy", "Kheir Eddine"],
  "M'Sila": ["M'Sila", "Boussaâda", "Sidi Aïssa", "Aïn El Hadjel", "Magra", "Ouled Derradj"],
  "Mascara": ["Mascara", "Sig", "Tighennif", "Ghriss", "Mohammadia", "Bou Hanifia"],
  "Ouargla": ["Ouargla", "Hassi Messaoud", "N'Goussa", "Rouissat", "Sidi Khouiled", "Aïn Beïda"],
  "Oran": ["Oran", "Es Sénia", "Bir El Djir", "Arzew", "Bethioua", "Gdyel", "Aïn Turck"],
  "El Bayadh": ["El Bayadh", "Bougtoub", "Rogassa", "Brézina", "El Abiodh Sidi Cheikh"],
  "Illizi": ["Illizi", "In Amenas", "Bordj Omar Driss"],
  "Bordj Bou Arréridj": ["Bordj Bou Arréridj", "Ras El Oued", "Bordj Zemoura", "El Achir", "Medjana"],
  "Boumerdès": ["Boumerdès", "Boudouaou", "Bordj Menaïel", "Dellys", "Naciria", "Thenia"],
  "El Tarf": ["El Tarf", "Bouteldja", "Ben M'Hidi", "El Kala", "Drean"],
  "Tindouf": ["Tindouf", "Oum El Assel"],
  "Tissemsilt": ["Tissemsilt", "Theniet El Had", "Bordj Bou Naama", "Lardjem"],
  "El Oued": ["El Oued", "Guemar", "Robbah", "Reguiba", "Debila", "Nakhla"],
  "Khenchela": ["Khenchela", "Kaïs", "Chechar", "Baghaï", "El Hamma", "Aïn Touila"],
  "Souk Ahras": ["Souk Ahras", "Sedrata", "Mechroha", "Merahna", "Taoura"],
  "Tipaza": ["Tipaza", "Cherchell", "Hadjout", "Koléa", "Fouka", "Bou Ismaïl"],
  "Mila": ["Mila", "Chelghoum Laïd", "Ferdjioua", "Grarem Gouga", "Oued Athmania"],
  "Aïn Defla": ["Aïn Defla", "Miliana", "Khemis Miliana", "El Attaf", "Djelida"],
  "Naâma": ["Naâma", "Mécheria", "Aïn Sefra", "Tiout"],
  "Aïn Témouchent": ["Aïn Témouchent", "Hammam Bouhadjar", "El Malah", "Beni Saf", "Terga"],
  "Ghardaïa": ["Ghardaïa", "Metlili", "Berriane", "Guerrara", "El Atteuf"],
  "Relizane": ["Relizane", "Oued Rhiou", "Mazouna", "Ammi Moussa", "El Matmar"],
  "Timimoun": ["Timimoun", "Aougrout", "Ouled Saïd", "Charouine"],
  "Bordj Badji Mokhtar": ["Bordj Badji Mokhtar", "Timiaouine"],
  "Ouled Djellal": ["Ouled Djellal", "Doucen", "Sidi Khaled"],
  "Béni Abbès": ["Béni Abbès", "Igli", "Kerzaz", "Tabelbala"],
  "In Salah": ["In Salah", "Foggaret Ezzaouia"],
  "In Guezzam": ["In Guezzam", "Tin Zaouatine"],
  "Touggourt": ["Touggourt", "N'Goussa", "Blidet Amor", "Megarine", "Taibet"],
  "Djanet": ["Djanet", "Bordj El Haouas"],
  "El M'Ghair": ["El M'Ghair", "Sidi Amrane", "Djamaa", "Still"],
  "El Meniaa": ["El Meniaa", "Hassi Gara", "Hassi Fehal"],
};
